/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EasyBuilder.java
 *
 * Created on Sep 22, 2011, 3:20:17 PM
 */
package net.psexton.easybuilder;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import javax.swing.UIManager;

/**
 *
 * @author PSexton
 */
public class EasyBuilder extends javax.swing.JFrame {
    private Model model;
    private File dataFile = new File("easybuilder_data");

    /** Creates new form EasyBuilder */
    public EasyBuilder() {
        initComponents();
        readSettingsFromFile();
        model = new Model(console);
    }
    
    private void updateActions() {
        // Get the buttonId and url text for each of our 5 items,
        // put them into a Map, and update the Model's buttonActions
        HashMap<String, String> actions = new HashMap<String, String>();
        
        // @FIX This is hacky, should really put these in an array and iterate over it
        if(!buttonId1.getText().isEmpty())
            actions.put(buttonId1.getText(), buttonUrl1.getText());
        if(!buttonId2.getText().isEmpty())
            actions.put(buttonId2.getText(), buttonUrl2.getText());
        if(!buttonId3.getText().isEmpty())
            actions.put(buttonId3.getText(), buttonUrl3.getText());
        if(!buttonId4.getText().isEmpty())
            actions.put(buttonId4.getText(), buttonUrl4.getText());
        if(!buttonId5.getText().isEmpty())
            actions.put(buttonId5.getText(), buttonUrl5.getText());
        
        model.setActions(actions);
    }
    
    /**
     * Reads in the portname, button ids, and urls from a data file.
     */
    private void readSettingsFromFile() {
        // If the file doesn't exist, (say it's the first time the app is run)
        // then don't try to read it in. Use empty values instead.
        if(dataFile.exists()) {
            try {
                BufferedReader reader = new BufferedReader(new FileReader(dataFile));
                portText.setText(reader.readLine());
                buttonId1.setText(reader.readLine());
                buttonUrl1.setText(reader.readLine());
                buttonId2.setText(reader.readLine());
                buttonUrl2.setText(reader.readLine());
                buttonId3.setText(reader.readLine());
                buttonUrl3.setText(reader.readLine());
                buttonId4.setText(reader.readLine());
                buttonUrl4.setText(reader.readLine());
                buttonId5.setText(reader.readLine());
                buttonUrl5.setText(reader.readLine());
                reader.close();
            }
            catch(FileNotFoundException ex) {
                throw new RuntimeException(ex);
            }
            catch(IOException ex) {
                throw new RuntimeException(ex);
            }
        }
        else {
            portText.setText("");
            buttonId1.setText("");
            buttonUrl1.setText("http://");
            buttonId2.setText("");
            buttonUrl2.setText("http://");
            buttonId3.setText("");
            buttonUrl3.setText("http://");
            buttonId4.setText("");
            buttonUrl4.setText("http://");
            buttonId5.setText("");
            buttonUrl5.setText("http://");
        }
    }
    
    /**
     * Writes out the portname, button ids, and urls to a data file.
     */
    private void writeSettingsToFile() {
        try {
            // overwrite the existing file
            dataFile.delete();
            dataFile.createNewFile();
            PrintWriter writer = new PrintWriter(dataFile);
            writer.println(portText.getText());
            writer.println(buttonId1.getText());
            writer.println(buttonUrl1.getText());
            writer.println(buttonId2.getText());
            writer.println(buttonUrl2.getText());
            writer.println(buttonId3.getText());
            writer.println(buttonUrl3.getText());
            writer.println(buttonId4.getText());
            writer.println(buttonUrl4.getText());
            writer.println(buttonId5.getText());
            writer.println(buttonUrl5.getText());
            writer.flush();
            writer.close();
        } 
        catch (FileNotFoundException ex) {
            throw new RuntimeException(ex);
        }
        catch(IOException ex) {
            throw new RuntimeException(ex);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        configPanel = new javax.swing.JPanel();
        portLabel = new javax.swing.JLabel();
        portText = new javax.swing.JTextField();
        buttonIdLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        buttonId1 = new javax.swing.JTextField();
        buttonUrl1 = new javax.swing.JTextField();
        buttonId2 = new javax.swing.JTextField();
        buttonUrl2 = new javax.swing.JTextField();
        buttonId3 = new javax.swing.JTextField();
        buttonUrl3 = new javax.swing.JTextField();
        buttonId4 = new javax.swing.JTextField();
        buttonUrl4 = new javax.swing.JTextField();
        buttonId5 = new javax.swing.JTextField();
        buttonUrl5 = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        consolePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyBuilder");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        portLabel.setText("Serial Port Name:");

        portText.setText("/dev/ttyUSB0");

        buttonIdLabel.setText("Button IDs:");

        urlLabel.setText("URLs:");

        buttonId1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        buttonId1.setText("5001");

        buttonUrl1.setText("http://mc.speechbanana.com/stream/04F9C751962280/broadcast");

        buttonId2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        buttonUrl2.setText("http://");

        buttonId3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        buttonUrl3.setText("http://");

        buttonId4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        buttonUrl4.setText("http://");

        buttonId5.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        buttonUrl5.setText("http://");

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectButton)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonId5)
                            .addComponent(buttonId4)
                            .addComponent(buttonId3)
                            .addComponent(buttonId2)
                            .addComponent(buttonId1)
                            .addComponent(portLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonUrl2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(urlLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonUrl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(portText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(buttonUrl3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(buttonUrl4, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(buttonUrl5, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))))
                .addContainerGap())
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIdLabel)
                    .addComponent(urlLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUrl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUrl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUrl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUrl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonId4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUrl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonId5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(connectButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configuration", configPanel);

        console.setColumns(20);
        console.setEditable(false);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consolePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consolePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Console", consolePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        updateActions();
        model.connect(portText.getText());
        
        // disable configuration and switch tabs
        portLabel.setEnabled(false);
        portText.setEnabled(false);
        buttonIdLabel.setEnabled(false);
        buttonId1.setEnabled(false);
        buttonId2.setEnabled(false);
        buttonId3.setEnabled(false);
        buttonId4.setEnabled(false);
        buttonId5.setEnabled(false);
        urlLabel.setEnabled(false);
        buttonUrl1.setEnabled(false);
        buttonUrl2.setEnabled(false);
        buttonUrl3.setEnabled(false);
        buttonUrl4.setEnabled(false);
        buttonUrl5.setEnabled(false);
        connectButton.setEnabled(false);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_connectButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(model.isConnected())
            model.disconnect();
        writeSettingsToFile();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    //  Exceptions setLookAndFeel may throw:
                    //      UnsupportedLookAndFeelException
                    //      ClassNotFoundException
                    //      InstantiationException
                    //      IllegalAccessException
                    throw new RuntimeException("Setting system look and feel", e);
                }
                
                new EasyBuilder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buttonId1;
    private javax.swing.JTextField buttonId2;
    private javax.swing.JTextField buttonId3;
    private javax.swing.JTextField buttonId4;
    private javax.swing.JTextField buttonId5;
    private javax.swing.JLabel buttonIdLabel;
    private javax.swing.JTextField buttonUrl1;
    private javax.swing.JTextField buttonUrl2;
    private javax.swing.JTextField buttonUrl3;
    private javax.swing.JTextField buttonUrl4;
    private javax.swing.JTextField buttonUrl5;
    private javax.swing.JPanel configPanel;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextArea console;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portText;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables
}
